sudo: false
language: python
env:
    - TOXENV=py27
    - TOXENV=py34
install:
    - pip install flake8 sphinx testimony tox
script:
    - flake8 .
    - make test-docstrings
    - make docs
    - tox
    # The `test-foreman-*` recipes require the presence of a Foreman
    # deployment, and they are lengthy. Don't run them on Travis.
notifications:
    irc: "chat.freenode.net#robottelo"
