sudo: false
language: python
install:
    - pip install -r requirements.txt
    - pip install -r requirements-optional.txt
script:
    - flake8 .
    - make test-docstrings
    - make test-robottelo
    # The `test-foreman-*` recipes require the presence of a Foreman
    # deployment, and they are lengthy. Don't run them on Travis.
notifications:
    irc: "chat.freenode.net#robottelo"
