name: Dependabot Auto Merge - ZStream
on:
  pull_request_target:
    branches-ignore:
      - master

jobs:
  dependabot:
    name: dependabot-auto-merge
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'dependencies')

    steps:
      - id: find-prt-comment
        name: Find the prt comment
        uses: peter-evans/find-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "trigger: test-robottelo"
          direction: last

      - name: Wait for PRT checks to get initiated
        if: steps.find-prt-comment.outputs.comment-body != ''
        run: |
          echo "Waiting for ~ 10 mins, PRT to be initiated." && sleep 600

      - name: Fetch and Verify the PRT status
        if: steps.find-prt-comment.outputs.comment-body != ''
        id: outcome
        uses: omkarkhatavkar/wait-for-status-checks@main
        with:
          ref: ${{ github.head_ref }}
          context: 'Robottelo-Runner'
          wait-interval: 60
          count: 100

      - name: Wait for other status checks to Pass
        id: waitforstatuschecks
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          ref: ${{ github.head_ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 60
          running-workflow-name: 'dependabot-auto-merge'
          allowed-conclusions: success,skipped

      - id: automerge
        name: Auto merge of dependabot PRs.
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "dependencies"
          MERGE_METHOD: "squash"
          MERGE_RETRIES: 5
          MERGE_RETRY_SLEEP: 900000

      - name: Auto Merge Status
        run: |
          if [ "${{ steps.automerge.outputs.mergeResult }}" == 'merged' ]; then
            echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} is Auto Merged !"
          else
            echo "::error Auto Merge for Pull request failed !"
            exit 1
          fi
